AllCops:
  Exclude:
    - 'rails-settings-cached.gemspec'
    - 'vendor/**/*'
    - 'lib/generators/settings/templates/*'

Documentation:
  Enabled: false

# don't prefer 'fail' over raise
SignalException:
  Enabled: false

LineLength:
  Max: 300

ClassVars:
  Enabled: false

FileName:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
